#!/usr/bin/env bash
set -e

USER=root
HOST=parts.team2337.com
APP=cheesy-parts
SCRIPT_NAME=parts_server

echo "Deploying $APP from Git master branch..."
echo
ssh $USER@$HOST "cd ~/$APP && git checkout -f && git pull && bundle install && bundle exec rake db:migrate && bundle exec ruby ${SCRIPT_NAME}_control.rb restart"
echo
echo "Deployed $APP."
